# Generated by Django 5.1.6 on 2025-05-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_ransaction_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ransaction_code',
            new_name='transaction_code',
        ),
    ]
